language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  -psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm install nyc
  - npm install coveralls
  - npm run coveralls 